config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='user')),
    path('', include('qa.urls', namespace='qa')),
]

qa/urls.py
from django.urls import path
from qa.views import (QuestionView, QuestionDetailView, QuestionListView, CreateAnswerView)

app_name = 'qa'
urlpatterns = [
    path('questions/', QuestionListView.as_view(), name='questions'),
    path('question/', QuestionView.as_view(), name='add-question'),
    path('question/<int:pk>/', QuestionDetailView.as_view(), name='question'),
    path('question/<int:pk>/answer/', CreateAnswerView.as_view(), name='add-answer'),
]

users/urls.py
from django.urls import path
from users import views
from django.contrib.auth import views as auth_view

app_name = 'users'
urlpatterns = [
    path('login', auth_view.LoginView.as_view(), name='login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('forgot-password', auth_view.PasswordResetView.as_view(), name='forgot-password'),
    path('password-reset-link-done', auth_view.PasswordResetDoneView.as_view(), name='password-reset-link-done'),
    path('password-reset', auth_view.PasswordChangeView.as_view(), name='reset-password'),
    path('logout', auth_view.LogoutView.as_view(), name='logout'),
]

qa/models.py
from django.db import models
from users.models import CustomUser
from django.shortcuts import reverse
# Create your models here.


class Question(models.Model):
    user = models.ForeignKey(to=CustomUser, related_name='questions', on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    question = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('qa:question', kwargs={'pk': self.id})

    def can_accept_answers(self, user):
        return user == self.user


class Answer(models.Model):
    user = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(to=Question, related_name='answers', on_delete=models.CASCADE)
    answer = models.TextField()
    accept = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.answer

    class Meta:
        ordering = ('-created_at',)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid
from users.managers import CustomUserManager
# Create your models here.


class CustomUser(AbstractUser):
    user_id = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    username = None
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    class Meta:
        verbose_name_plural = 'Users'
        verbose_name = 'User'

    def __str__(self):
        return self.email

qa/forms.py
from django import forms
from qa.models import Question, Answer
from users.models import CustomUser


class QuestionForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput,
                                  queryset=CustomUser.objects.all(), disabled=True, )

    class Meta:
        model = Question
        fields = ['title', 'question', 'user']


class AnswerForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput,
                                  queryset=CustomUser.objects.all(), disabled=True, )
    question = forms.ModelChoiceField(widget=forms.HiddenInput,
                                      queryset=Question.objects.all(), disabled=True, )

    class Meta:
        model = Answer
        fields = ['answer', 'question', 'user']


class AnswerAcceptanceForm(forms.ModelForm):
    accepted = forms.BooleanField(widget=forms.HiddenInput, required=False,)

    class Meta:
        model = Answer
        fields = ['accepted',]

users/forms.py
from users.models import CustomUser
from django.contrib.auth.forms import (UserCreationForm, UserChangeForm,)


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('email',)

qa/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from qa.forms import QuestionForm, AnswerForm, AnswerAcceptanceForm
from qa.models import Question, Answer
from django.http import HttpResponseBadRequest

# Create your views here.


class QuestionListView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'qa/questions.html'


class QuestionView(CreateView):
    form_class = QuestionForm
    template_name = 'qa/add_question.html'

    def get_initial(self):
        return {
            "user": self.request.user.id
        }

    # def form_valid(self, form):
    #     action = self.request.method.POST.get('action',)
    #     if action == 'SAVE':
    #         return super.form_valid(form)
    #     elif action == 'PREVIEW':
    #         preview = Question(
    #             question=form.cleaned_data['question'],
    #             title=form.cleaned_data['title'],
    #         )
    #         context = self.get_context_data(preview=preview)
    #         return self.render_to_response(context=context)
    #     return HttpResponseBadRequest()


class QuestionDetailView(DetailView):
    model = Question
    template_name = 'qa/question_details.html'
    context_object_name = 'question_detail'

    ACCEPT_FORM = AnswerAcceptanceForm(initial={'accepted': True})
    REJECTED_FORM = AnswerAcceptanceForm(initial={'accepted': False})

    def get_context_data(self, **kwargs):
        context = super(QuestionDetailView, self).get_context_data()
        context.update({
            'answer_form': AnswerAcceptanceForm(initial={
                'user': self.request.user,
                'question': self.object.id,
            })
        })
        if self.object.can_accept_answers:
            context.update({
                'accept_form': self.ACCEPT_FORM,
                'reject_form': self.REJECTED_FORM,
            })
        return context


class CreateAnswerView(CreateView):
    form_class = AnswerForm
    template_name = 'qa/add_answer.html'

    def get_initial(self):
        return {
            'user': self.request.user.id,
            'question': self.get_question().id,
        }

    def get_context_data(self, **kwargs):
        return super().get_context_data(question=self.get_question(), **kwargs)

    def get_success_url(self):
        return self.object.question.get_absolute_url()

    def get_question(self):
        return Question.objects.get(pk=self.kwargs['pk'])

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from users.forms import CustomUserCreationForm

# Create your views here.


class RegisterView(CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('#')

qa/templates/qa/add_answer.html
{% extends 'qa/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Add Answer
{% endblock %}


{% block main %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
<!--          1 of 3-->
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-sm-4">
                    <h4 class="mt-5"><a href="{% url 'qa:questions' %}" type="button" class="btn btn-secondary"> Back </a></h4>
                </div>
                <div class="col-sm-8">
                    <h4 class="mt-5">Add Answer</h4>
                </div>
            </div>
            <hr>
            <div class="container-fluid">
                <form class="was-validated" method="post">
                    {% csrf_token %}
                <div class="mb-3">
                  <label for="exampleFormControlTextarea1" class="form-label">Answer<span>*</span></label>
                  <textarea class="form-control" name="answer" id="exampleFormControlTextarea1" rows="3" required required
                            placeholder="Enter more detail info about your question"></textarea>
                </div>
                    <div class="d-grid gap-2 col-6 mx-auto">
                      <button class="btn btn-primary" type="submit">SUBMIT ANSWER</button>
                    </div>
                </form>
            </div>

        </div>


        <div class="col-md-2">
<!--          3 of 3-->
        </div>
    </div>
</div>
{% endblock %}

qa/templates/qa/add_question.html
{% extends 'qa/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    New Question
{% endblock %}


{% block main %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
<!--          1 of 3-->
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-sm-4">
                    <h4 class="mt-5"><a href="{% url 'qa:questions' %}" type="button" class="btn btn-secondary"> Back </a></h4>
                </div>
                <div class="col-sm-8">
                    <h4 class="mt-5">New Question</h4>
                </div>
            </div>
            <hr>
            <div class="container-fluid">
                <form class="was-validated" method="post">
                    {% csrf_token %}
                <div class="mb-3">
                  <label for="exampleFormControlInput1" class="form-label">Question<span>*</span></label>
                  <input type="text" class="form-control" name="title" id="exampleFormControlInput1" required placeholder="How to fix non-object type str">
                </div>
                <div class="mb-3">
                  <label for="exampleFormControlTextarea1" class="form-label">Details Question<span>*</span></label>
                  <textarea class="form-control" name="question" id="exampleFormControlTextarea1" rows="3" required required
                            placeholder="Enter more detail info about your question"></textarea>
                </div>
                    <div class="d-grid gap-2 col-6 mx-auto">
                      <button class="btn btn-primary" type="submit">SUBMIT QUESTION</button>
                    </div>
                </form>
            </div>

        </div>


        <div class="col-md-2">
<!--          3 of 3-->
        </div>
    </div>
</div>
{% endblock %}

qa/templates/qa/base.html
<!doctype html>
<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="description" content="">
  <title>{% block title %} {% endblock %}</title>

  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">


    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
  <style>
    body {
    background-color: #fcfcfd;
}

  .question-container {
      width: 90%;
      padding: 5px;
      margin-bottom: 5px;
      background-color: #ffffff;
      border-radius: 5px;
  }

  .question-details {
      margin: 10px, 50px;
      padding-left: 30px;
      padding-right: 30px;
  }

  .question-details h6 {
      font-weight: 30px;
      font-size: 15px;
      margin-bottom: 10px;
      color: #03a5fc;
  }
  .question-details p {
      font-size: 14px;
      line-height: 1px;
      color: #404040;
  }

  .icon {
      width: 25px;
      height: 25px;
      background-color: #eee;
      border-radius: 10px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 39px
  }
  .c-details h6 {
    font-size: 10px;
    font-weight: 50px;
  }

.c-details span{
    font-size: 10px;
    font-weight: 50px;
    color: #7a7a7a;
  }
  .pl4 {
    padding-left: 30px;
  }

  }

  .badge {
    margin-top: 10px;
    padding-right: 30px;
  }

  .answer-p {
    background-color: #e4f5eb;
    color: #707070;
    padding: 12px;
    border-radius: 5px;
  }
  .badge span {
      background-color: #6ab056;
      padding: 6px;
      border-radius: 5px;
      display: flex;
      color: #fff;
      justify-content: center;
      align-items: center
  }

  .progress {
      height: 10px;
      border-radius: 10px
  }

  .progress div {
      background-color: red
  }

  .text1 {
      font-size: 14px;
      font-weight: 600
  }
</style>
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
</svg>

{% block main %}

{% endblock %}


<script>
    function loadinggradient(){
        document.getElementById('loadingprogress').style.display='block';

    }
    function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
}
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
</body>
</html>

qa/templates/qa/question_details.html
{% extends 'qa/base.html' %}

{% block title %}
    Question Details
{% endblock %}


{% block main %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
<!--          1 of 3-->
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-sm-4">
                    <h4 class="mt-5"><a href="{% url 'qa:questions' %}" type="button" class="btn btn-secondary">
                        Back
                    </a>
                    </h4>
                </div>
                <div class="col-sm-8">
                    <h4 class="mt-5">Question Details</h4>
                </div>
            </div>
            <hr>
            <div class="container-fluid">
            <div class="row">
                <div class="row">
                    <div class="col-sm-12">
                        <h4>{{ question_detail.title }}</h4>
                    </div>
                </div>
               <div class="col-sm-2">
                   <p>Asked by: {{ question_detail.user }}</p>
               </div>

               <div class="col-sm-2">
                   <p>Answers: 10 </p>
               </div>
                <div class="col-sm-3">
                   <p>Mark as answered? Yes </p>
               </div>
            </div>
                <div class="mt-4 mb-3">
                    <p>
                        {{ question_detail.question }}
                    </p>

                    <div>
                        <h6><small>Category:</small>
                        <span class="badge bg-light text-dark">Python</span>
                        <span class="badge bg-light text-dark">Django</span>
                        </h6>
                    </div>

                </div><br>
                    <div class="mt-4 mb-3">
                        <h4>Answers</h4>
                    <p class="answer-p">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        Lorem Ipsum has been the industry's standard dummy text ever since the 1500s
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                        <br><br><small>by: Jonas</small>
                    </p>
                 </div>

                <p class="answer-p">
                    {{question_detail.}}
                    <br><br><small>by: Jonas</small>
                </p>
            </div>

            <div>

            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-5" style="margin-right: 15px">
              <a type="button" href="{% url 'qa:add-answer' question_detail.id %}" class="btn btn-outline-primary">Add Answer</a><br>
            </div>

    </div>
        <div class="col-md-2">
<!--          3rd column-->
        </div>
    </div>
</div>
{% endblock %}

qa/templates/qa/questions.html
{% extends 'qa/base.html' %}

{% block title %}

{% endblock %}


{% block main %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
<!--          1 of 3-->
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-sm-8">
                    <h4 class="mt-4">All Questions</h4>
                </div>
                <div class="col-sm-4">
                    <h4 class="mt-4"><a href="{% url 'qa:add-question' %}" type="button" class="btn btn-primary">Add New Question</a></h4>
                </div>
            </div>
            <hr>
            {% for question in questions %}
                    {% if question == '' %}
                    <p>No Question, Ask a question</p>
                    {% else %}
            <div class="question-container">
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center pl4 mt-3">
                        <div class="icon"> <i class="bx bxl-mailchimp"></i> </div>
                        <div class="ms-2 c-details">
                            <h6 class="mb-0">Mailchimp</h6> <span class="day">1 days ago</span>
                        </div>
                    </div>
                    <div class="badge"> <span class="">Answered</span> </div>
                </div>

                    <div class="question-details mt-4 mb-3">
                        <h6>{{ question.title }}</h6>
                        <p>{{ question.question }}
                            <a type="button" class="btn btn-link" href="{% url 'qa:question' question.pk %}"><big>View Question Details</big></a>
                        </p>
                        <small>Category:</small>
                        <span class="badge bg-light text-dark">Python</span>
                        <span class="badge bg-light text-dark">Django</span>
                    </div>

            </div>
            {% endif %}
            {% endfor %}
    </div>
        <div class="col-md-2">
<!--          3rd column-->
        </div>
    </div>
</div>
{% endblock %}

users/templates/_header.html
<!--        <header class="w3-bar   w3-top  w3-white notranslate">-->
<!--          <div class="w3-bar-item  w3-wide"><img src="https://i.ibb.co/SKqmC0Y/maskable-icon.png" style="width:55px; height:55px; border-radius:55px; "></div>-->
<!--          <a href="#" class="w3-bar-item w3-button  w3-right" onclick="document.getElementById('id01').style.display='block'"><span class="material-icons notranslate">-->
<!--        translate-->
<!--        </span></a>-->

<!--        </header>-->

users/templates/base.html
<!doctype html>
<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="description" content="">
  <title>{% block title %} {% endblock %}</title>

  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">


    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">

  <style>
<!--    body {-->
<!--    background-color: #FFEBEE-->
<!--}-->

.card_registration {
    background-color: #FDFDFD;
    border: none;
    border-radius: 5px;
    padding: 1px 30px;
    box-shadow: 0px 6px 18px 2px rgba(230,230,230,0.5);
    -webkit-box-shadow: 0px 6px 18px 2px rgba(230,230,230,0.5);
    -moz-box-shadow: 0px 6px 18px 2px rgba(230,230,230,0.5);
}
</style>
</head>
<body>

{% block main %}

{% endblock %}


<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
}
</script>
<script>
    function loadinggradient(){
        document.getElementById('loadingprogress').style.display='block';

    }
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
</body>
</html>